set(sources ${sources}
	src/CLIK/Array.h
	src/CLIK/GFx/Core/UIComponent.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/CLIK/keyvalue.h
	src/CLIK/pictureback.h
	src/PCH.h
	src/data/actordata.h
	src/handle/dialogueactorhandle.h
	src/hook.h
	src/hook/dialoguemenu.h
	src/main.cpp
	src/scaleform/menu/dialogueinfomenu.h
	src/scaleform/scaleform.h
	src/setting/setting.h
	src/util/constant.h
	src/util/menukeys.h
	src/util/offset.h
	src/util/util.h
)
