set(sources ${sources}
	src/CLIK/Array.h
	src/CLIK/GFx/Core/UIComponent.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/PCH.h
	src/data/actordata.h
	src/event.h
	src/event/menuevent.h
	src/handle/dialogactorhandle.h
	src/hook.h
	src/hook/dialogmenu.h
	src/main.cpp
	src/scaleform/menu/dialoginfomenu.h
	src/scaleform/scaleform.h
	src/setting/setting.h
	src/util/constant.h
	src/util/util.h
)
